export const AUTH_SIGN_UP_REQUEST= "AUTH_SIGN_UP_REQUEST"
export const AUTH_SIGN_UP_SUCCESS= "AUTH_SIGN_UP_SUCCESS"
export const AUTH_SIGN_UP_FAIL= "AUTH_SIGN_UP_FAIL"

export const AUTH_SIGN_IN_REQUEST= "AUTH_SIGN_IN_REQUEST"
export const AUTH_SIGN_IN_SUCCESS= "AUTH_SIGN_IN_SUCCESS"
export const AUTH_SIGN_IN_FAIL= "AUTH_SIGN_IN_FAIL"

export const AUTH_SIGN_OUT_REQUEST= "AUTH_SIGN_OUT_REQUEST"
export const AUTH_SIGN_OUT_SUCCESS= "AUTH_SIGN_OUT_SUCCESS"
export const AUTH_SIGN_OUT_FAIL= "AUTH_SIGN_OUT_FAIL"

export const GET_AUTH_USER_REQUEST= "GET_AUTH_USER_REQUEST"
export const GET_AUTH_USER_SUCCESS= "GET_AUTH_USER_SUCCESS"
export const GET_AUTH_USER_FAIL= "GET_AUTH_USER_FAIL"