export const GET_PRODUCT_LIST_REQUEST= "GET_PRODUCT_LIST_REQUEST"
export const GET_PRODUCT_LIST_SUCCESS= "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_FAIL= "GET_PRODUCT_LIST_FAIL"

export const GET_PRODUCT_SLIDE_REQUEST= "GET_PRODUCT_SLIDE_REQUEST"
export const GET_PRODUCT_SLIDE_SUCCESS= "GET_PRODUCT_SLIDE_SUCCESS"
export const GET_PRODUCT_SLIDE_FAIL= "GET_PRODUCT_SLIDE_FAIL"

export const GET_PRODUCT_DETAIL_REQUEST= "GET_PRODUCT_DETAIL_REQUEST"
export const GET_PRODUCT_DETAIL_SUCCESS= "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAIL= "GET_PRODUCT_DETAIL_FAIL"