export const INDEX= "/"
export const CART= "/shopping-cart"
export const SIGN_IN= "/sign-in"
export const SIGN_UP= "/sign-up"
export const PRODUCT= "/product"
export const PROFILE= "/profile"
export const NOT_FOUND= "*"